name: Postman Testes API
on: push
jobs:
  test:
    name: Run Testes
    runs-on: ubuntu-latest
    
    steps:
    - name: Clonar Repositorio
      uses: actions/checkout@v2

    - name: Install Newman and Reporter
      run: |
        npm install -g newman newman-reporter-htmlextra

    - name: Run Postman Collection
      run: |        
        newman run PUT_collection.json  -e postman_environment.json  --reporters cli,htmlextra --reporter-htmlextra-export ./results/report.html 
    - name: Salvar arquivos
      if: ${{always()}}
      uses: actions/upload-artifact@v3
      with:
        name: Relatorio
        path: ./results
        
    - name: Upload to Pages Artifact
      uses: actions/upload-artifact@v3
      with:
        path: ./results/

   
