name: Postman API
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y nodejs npm
        npm install -g newman newman-reporter-htmlextra

    - name: Run Postman Tests
      run: |
        mkdir -p results
        newman run cristianEisenhut-postman_collection.json -e cristianEisenhut-postman_environment.json -r htmlextra --reporter-htmlextra-export ./results/results.html

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1
      with:
        path: ./results
