name: Postman Testes API
on: push
jobs:
  test:
    name: Run Testes
    runs-on: ubuntu-latest

    permissions:
     contents: read
     pages: write
     id-token: write
    environment:
      name: github-pages
      url: https://cristiancfe.github.io/Postman_ci/report.html

    steps:
    - name: checkout Repository 
      uses: actions/checkout@v2
                      
    - name: Step 2 Install Newman-Reporter-Htmlextra
      run: sudo npm install -g newman-reporter-htmlextra
        
      # Runs a set of commands using the runners shell
    - name: Step 3 Execute collection
      run: newman run collection.json -e environment.json --reporters cli, -r htmlextra --reporter-htmlextra-export ./results/Report.html

    - name: Arquive API Postman
      if: ${{always() }}
      uses: actions/upload-artifact@v3
      with:
        name: Postman API
        path: ./results
    - name: Setup Pages
      uses: actions/configure-pages@v2

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./results/

    - name: Deploy to Github Pages
      id: deployment
      uses: actions/deploy-pages@v1
