name: Postman API
on: push
jobs:
  test:
    name: Run Testes
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: https://cristiancfe.github.io/postman_ci/report.html

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        npm install -g newman
        npm i -g newman-reporter-htmlextra

    - name: Run Postman Tests
      run: |
        mkdir -p ./results/newman
        newman run cristianEisenhut-postman_collection.json -e cristianEisenhut-postman_environment.json -r htmlextra --reporter-htmlextra-export ./results/report.html

    - name: Archive Postman Results
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: Postman Relatório
        path: ./results/newman

    # Configuração do Pages
    - name: Setup Pages
      uses: actions/configure-pages@v2

    - name: Copy Report to Root for Pages
      run: cp -r ./results/newman/* .

    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
