name: Postman API
on: push
jobs:
  test:
    name: Run Testes
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: https://cristiancfe.github.io/postman_ci/report.html
     

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        npm install  newman
        npm install newman-reporter-htmlextra
        npm install faker-br
        node --version
        newman --version
       
    - name: Testes Postman API
      run: |       
       newman run cristianEisenhut-postman_collection.json -e cristianEisenhut-postman_environment.json -r htmlextra --reporter-htmlextra-export  ./results/report.html
 
    - name: Archive Postman results
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: report
        path: ./results

    # Configuração do Pages
    - name: Setup Pages
      uses: actions/configure-pages@v2

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./results
        
    - name: Deploy to Github Pages
      id: deployment
      uses: actions/deploy-pages@v1
      
